#!/bin/bash

# ---- autostart
#systemctl --user import-environment DISPLAY WAYLAND_DISPLAY SWAYSOCK
#dbus-update-activation-environment --systemd DISPLAY WAYLAND_DISPLAY SWAYSOCK
dbus-update-activation-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP=wlroots
exec wl-paste --type text --watch cliphist store &
exec wl-paste --type image --watch cliphist store &
exec syncthing serve --no-browser &
exec kdeconnect-indicator &
exec wp &
exec pgrep swayidle || swayidle before-sleep swaylock &
exec pgrep lowbat || lowbat &
exec start-waybar &
exec dunst &
exec fcitx5 -d &
#exec sh -c 'sleep 0.5 && udiskie -t &' & # Automounting removable media, tray icon

# ---- variables
term="foot"
browser="firefox"
wm="rivercarro"

# ---- general
# window (layout) manager
riverctl default-layout $wm
#rivertile -view-padding 0 -outer-padding 0 -main-ratio 0.55 &
rivercarro -inner-gaps 0 -outer-gaps 0 -main-ratio 0.55 &

# focus
riverctl focus-follows-cursor normal

# borders & background
riverctl border-width 1
riverctl border-color-focused 0xf5c2e7
riverctl border-color-unfocused 0x1e1e2e
riverctl background-color 0x000000

# Set input and keyboard repeat rate
riverctl keyboard-layout -options "grp:ctrl_space_toggle" "vmk" # -options "caps:swapescape"
riverctl set-repeat 50 300

# --- rules
riverctl rule-add -app-id '*' ssd # make everything use server side decorations so borders don't break

# ---- binds
# programs
riverctl map normal Super Return spawn $term
riverctl map normal Super P spawn 'rofi -show drun'
riverctl map normal Super+Alt P spawn 'rofi -show run'
riverctl map normal Super V spawn $browser
riverctl map normal Super B spawn 'pidof waybar && killall -SIGUSR1 waybar'
riverctl map normal Super+Alt B spawn 'pidof waybar && killall -SIGUSR2 waybar || start-waybar &'
riverctl map normal Super+Shift V spawn 'cliphist list | rofi -dmenu | cliphist decode | wl-copy'
riverctl map normal Super equals spawn 'rofi -show calc -modi calc -no-show-match -no-sort'
riverctl map normal Super O spawn "$term wp -i"
riverctl map normal Super N spawn 'bmn'
riverctl map normal Super N spawn "$term tmux attach -t rr || tmux new -s rr"
riverctl map normal Super N spawn 'kill -9 $(pidof syncthing) && notify-send "SYNCTHING KILLED"'
riverctl map normal None Print spawn 'filename=$HOME/Pictures/grim/$(date +%F_%T).png && slurp | grim -g - $filename && wl-copy -t image/png < $filename'
riverctl map normal Alt Print spawn 'filename=$HOME/Pictures/grim/$(date +%F_%T).png && grim $filename && wl-copy -t image/png < $filename'

# brightness, media, sound, mic
# works in lockscreen
for mode in normal locked; do
	riverctl map $mode None XF86AudioRaiseVolume		spawn 'pactl set-sink-volume 0 +5%'
	riverctl map $mode None XF86AudioLowerVolume		spawn 'pactl set-sink-volume 0 -5%'
	riverctl map $mode Shift XF86AudioRaiseVolume		spawn 'pactl set-sink-volume 0 +1%'
	riverctl map $mode Shift XF86AudioLowerVolume		spawn 'pactl set-sink-volume 0 -1%'
	riverctl map $mode None XF86AudioMute				spawn 'pactl set-sink-mute 0 toggle'

	riverctl map $mode Alt XF86AudioRaiseVolume			spawn 'pactl set-source-volume 0 +5%'
	riverctl map $mode Alt XF86AudioLowerVolume			spawn 'pactl set-source-volume 0 -5%'
	riverctl map $mode Alt+Shift XF86AudioRaiseVolume	spawn 'pactl set-source-volume 0 +1%'
	riverctl map $mode Alt+Shift XF86AudioLowerVolume	spawn 'pactl set-source-volume 0 -1%'
	riverctl map $mode None XF86AudioMicMute			spawn 'pactl set-source-mute 0 toggle'

	riverctl map $mode None XF86AudioPlay		 		spawn 'playerctl play-pause'
	riverctl map $mode None XF86AudioNext		 		spawn 'playerctl next'
	riverctl map $mode None XF86AudioPrev		 		spawn 'playerctl previous'
	riverctl map $mode None Cancel		 				spawn 'playerctl play-pause'
	riverctl map $mode None XF86Favourites		 		spawn 'playerctl next'
	riverctl map $mode None XF86Go				 		spawn 'playerctl previous'

	riverctl map $mode None XF86MonBrightnessUp			spawn 'brightnessctl s +10%'
	riverctl map $mode None XF86MonBrightnessDown		spawn 'brightnessctl s 10%-'
	riverctl map $mode Shift XF86MonBrightnessUp		spawn 'brightnessctl s +1%'
	riverctl map $mode Shift XF86MonBrightnessDown		spawn 'brightnessctl s 1%-'
done

# power
# works in lockscreen
for mode in normal locked; do
	riverctl map $mode Super F12 spawn 'loginctl poweroff'
	riverctl map $mode Super F11 spawn 'loginctl reboot'
	riverctl map $mode Super F10 spawn 'loginctl suspend'
done
riverctl map normal Super F9 spawn 'swaylock'

# mpd mode
riverctl declare-mode mpd
riverctl map normal Super S enter-mode mpd
riverctl map mpd None Escape enter-mode normal
riverctl map mpd None Space spawn 'mpc toggle'
riverctl map mpd None N spawn 'mpc next'
riverctl map mpd None J spawn 'mpc next'
riverctl map mpd None P spawn 'mpc prev'
riverctl map mpd None K spawn 'mpc prev'
riverctl map mpd None S spawn 'mpc shuffle'
riverctl map mpd None R spawn 'mpc random'
riverctl map mpd None L spawn 'mpc repeat'
riverctl map mpd None C spawn 'mpc clear'
riverctl map mpd None equal spawn "sh -c 'mpc volume +10 && notify-send -t 300 $(mpc volume)'"
riverctl map mpd None minus spawn "sh -c 'mpc volume -10 && notify-send -t 300 $(mpc volume)'"
riverctl map mpd None q spawn "$term mpq"
riverctl map mpd None a spawn "$term mqa"
riverctl map mpd None d spawn "$term mqd"
riverctl map mpd None g spawn "$term mqg"


# river
riverctl map normal Super X close
riverctl map normal Super+Shift T exit

# mouse
riverctl map-pointer normal Super BTN_LEFT move-view
riverctl map-pointer normal Super BTN_RIGHT resize-view
riverctl map-pointer normal Super BTN_MIDDLE toggle-float

# master and slave
riverctl map normal Super+Shift Return zoom
# Super+J and Super+K to focus the next/previous view in the layout stack
riverctl map normal Super J focus-view next
riverctl map normal Super K focus-view previous
# Super+Shift+J and Super+Shift+K to swap the focused view with the next/previous view in the layout stack
riverctl map normal Super+Shift J swap next
riverctl map normal Super+Shift K swap previous
# Super+H and Super+L to decrease/increase the main ratio of $wm(1)
riverctl map normal Super H send-layout-cmd $wm "main-ratio -0.05"
riverctl map normal Super L send-layout-cmd $wm "main-ratio +0.05"
# Super+Shift+H and Super+Shift+L to increment/decrement the main count of $wm(1)
riverctl map normal Super+Shift H send-layout-cmd $wm "main-count +1"
riverctl map normal Super+Shift L send-layout-cmd $wm "main-count -1"

# multi monitor
# Super+Period and Super+Comma to focus the next/previous output
riverctl map normal Super Period focus-output next
riverctl map normal Super Comma focus-output previous
# Super+Shift+{Period,Comma} to send the focused view to the next/previous output
riverctl map normal Super+Shift Period send-to-output next
riverctl map normal Super+Shift Comma send-to-output previous

# tags
keys=()
for i in $(seq 1 5)
do
	keys+=("$i")
done
keys+=("Q")
keys+=("W")
keys+=("E")
keys+=("R")
keys+=("grave")

for i in $(seq 0 9)
do
    tags=$((1 << $i))

    # Super+[1-9] to focus tag [0-8]
    riverctl map normal Super "${keys[$i]}" set-focused-tags $tags

    # Super+Shift+[1-9] to tag focused view with tag [0-8]
    riverctl map normal Super+Shift "${keys[$i]}" set-view-tags $tags

    # Super+Control+[1-9] to toggle focus of tag [0-8]
    riverctl map normal Super+Control "${keys[$i]}" toggle-focused-tags $tags

    # Super+Shift+Control+[1-9] to toggle tag [0-8] of focused view
    riverctl map normal Super+Shift+Control "${keys[$i]}" toggle-view-tags $tags
done

# Super+0 to focus all tags
# Super+Shift+0 to tag focused view with all tags
all_tags=$(((1 << 32) - 1))
riverctl map normal Super 0 set-focused-tags $all_tags
riverctl map normal Super+Shift 0 set-view-tags $all_tags

# dynamic layouts
# Super+Space to toggle float
riverctl map normal Super Space toggle-float
# Super+F to toggle fullscreen
riverctl map normal Super F toggle-fullscreen

# Super+M for Monocle layout
riverctl map normal Super M send-layout-cmd rivercarro "main-location monocle"
# Super+T to get back to Master and slave layout
riverctl map normal Super T send-layout-cmd rivercarro "main-location left"
