# A TOML linter such as https://taplo.tamasfe.dev/ can use this schema to validate your config.
# If you encounter any issues, please make an issue at https://github.com/yazi-rs/schemas.
"$schema" = "https://yazi-rs.github.io/schemas/keymap.json"

[[manager.prepend_keymap]]
	on = "j"
	run = "plugin arrow 1"
	desc = "Move selection downwards, or wrap."
[[manager.prepend_keymap]]
	on = "k"
	run = "plugin arrow -1"
	desc = "Move selection upwards, or wrap."
[[manager.prepend_keymap]]
	on = "l"
	run = "plugin smart-enter"
	desc = "Enter the child directory, or open the file"
[[manager.prepend_keymap]]
	on = "="
	run = """shell 'printf "Mode Bits: "; read ans; chmod $ans "$@"' --block --confirm"""
	desc = "chmod"
[[manager.prepend_keymap]]
	on = "!"
	run = 'shell "$SHELL" --block --confirm'
	desc = "Open shell here"
[[manager.prepend_keymap]]
	on  = "M"
	run = "plugin mount"
[[manager.prepend_keymap]]
	on   = [ "c", "a" ]
	run  = "plugin compress"
	desc = "Archive selected files"
[[manager.prepend_keymap]]
	on = "z"
	run = "plugin zoxide"
	desc = "zoxide"
[[manager.prepend_keymap]]
	on = "Z"
	run = "plugin fzf"
	desc = "fzf"
