# A TOML linter such as https://taplo.tamasfe.dev/ can use this schema to validate your config.
# If you encounter any issues, please make an issue at https://github.com/yazi-rs/schemas.
"$schema" = "https://yazi-rs.github.io/schemas/keymap.json"

[[mgr.prepend_keymap]]
	on = "l"
	run = "plugin smart-enter"
	desc = "Enter the child directory, or open the file"
[[mgr.prepend_keymap]]
	on = "="
	run = """shell 'printf "Mode Bits: "; read ans; chmod $ans "$@"' --block --confirm"""
	desc = "chmod"
[[mgr.prepend_keymap]]
	on = "!"
	run = 'shell "$SHELL" --block --confirm'
	desc = "Open shell here"
[[mgr.prepend_keymap]]
	on  = "M"
	run = "plugin mount"
[[mgr.prepend_keymap]]
	on   = [ "c", "a" ]
	run  = "plugin compress"
	desc = "Archive selected files"
[[mgr.prepend_keymap]]
	on = "z"
	run = "plugin zoxide"
	desc = "zoxide"
[[mgr.prepend_keymap]]
	on = "Z"
	run = "plugin fzf"
	desc = "fzf"
[[mgr.prepend_keymap]]
	on = [ "g", "r" ]
	run = "cd /run/media/$USER"
	desc = "Go to mounted"
[[mgr.prepend_keymap]]
	on = [ "g", "d" ]
	run = "noop"
[[mgr.prepend_keymap]]
	on = [ "c", "b" ]
	run = [ 'shell -- for path in "$@"; do echo "file://$path"; done | wl-copy -t text/uri-list' ]
	desc = "Copy the file binary"
