# Config for Alacritty (.toml - for newer versions of Alacritty)
#                    __
#      _  __ __ _   / /__
#     | |/ //  ' \ /  '_/
# by  |___//_/_/_//_/\_\
# @vmkxyz on gitlab and github

# [colors.bright]
# black = "#555555"
# blue = "#5555FF"
# cyan = "#55FFFF"
# green = "#55FF55"
# magenta = "#FF55FF"
# red = "#FF5555"
# white = "#FFFFFF"
# yellow = "#FFFF55"

# [colors.normal]
# black = "#000000"
# blue = "#0026E6"
# cyan = "#00AAAA"
# green = "#00AA00"
# magenta = "#AA00AA"
# red = "#AA0000"
# white = "#AAAAAA"
# yellow = "#AA5500"
#
#[colors.dim]

# [colors.primary]
# background = "#00040a"
# foreground = "#FFFFFF"

[colors.primary]
background = "#09090f"
foreground = "#CDD6F4"
dim_foreground = "#CDD6F4"
bright_foreground = "#CDD6F4"

[colors.cursor]
text = "#1E1E2E"
cursor = "#F5E0DC"

[colors.vi_mode_cursor]
text = "#1E1E2E"
cursor = "#B4BEFE"

[colors.search.matches]
foreground = "#1E1E2E"
background = "#A6ADC8"

[colors.search.focused_match]
foreground = "#1E1E2E"
background = "#A6E3A1"

[colors.footer_bar]
foreground = "#1E1E2E"
background = "#A6ADC8"

[colors.hints.start]
foreground = "#1E1E2E"
background = "#F9E2AF"

[colors.hints.end]
foreground = "#1E1E2E"
background = "#A6ADC8"

[colors.selection]
text = "#1E1E2E"
background = "#F5E0DC"

[colors.normal]
black = "#45475A"
red = "#F38BA8"
green = "#A6E3A1"
yellow = "#F9E2AF"
blue = "#89B4FA"
magenta = "#F5C2E7"
cyan = "#94E2D5"
white = "#BAC2DE"

[colors.bright]
black = "#585B70"
red = "#F38BA8"
green = "#A6E3A1"
yellow = "#F9E2AF"
blue = "#89B4FA"
magenta = "#F5C2E7"
cyan = "#94E2D5"
white = "#A6ADC8"

[colors.dim]
black = "#45475A"
red = "#F38BA8"
green = "#A6E3A1"
yellow = "#F9E2AF"
blue = "#89B4FA"
magenta = "#F5C2E7"
cyan = "#94E2D5"
white = "#BAC2DE"

[[colors.indexed_colors]]
index = 16
color = "#FAB387"

[[colors.indexed_colors]]
index = 17
color = "#F5E0DC"

[cursor]
style = { shape = "Underline", blinking = "On" }
blink_interval = 500
unfocused_hollow = true
vi_mode_style = "Beam"

[font]
size = 10
normal = { family = "SauceCodePro Nerd Font", style = "Regular" }
bold = { style = "Bold" }
italic = { style = "Italic" }
bold_italic = { style = "Bold Italic" }

[scrolling]
history = 50000
multiplier = 3

[window]
padding = { x = 2, y = 0 }
dynamic_padding = true
decorations = "none"
opacity = 0.8
startup_mode = "Windowed"
